<?php

/**
 * @file
 * Defines management/helper/display functions for page like content.
 */

define('ISLANDORA_PAGED_CONTENT_EDIT_OCR', 'Edit existing OCR stream');

// @codingStandardsIgnoreStart
// XXX: Remove this at some point in the future.
define('ISLANDORA_EDIT_OCR', ISLANDORA_PAGED_CONTENT_EDIT_OCR);
// @codingStandardsIgnoreEnd

/**
 * Implements hook_menu().
 */
function islandora_paged_content_menu() {
  return array(
    'admin/islandora/paged_content' => array(
      'title' => 'Paged Content Module',
      'description' => 'Configuration for the Paged Content solution pack.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_paged_content_admin_settings_form'),
      'access arguments' => array('administer site configuration'),
      'file' => 'includes/admin.form.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
  );
}

/**
 * Implements hook_theme().
 */
function islandora_paged_content_theme() {
  return array(
    'islandora_paged_content_page_navigator' => array(
      'file' => 'theme/theme.inc',
      'variables' => array(
        'object' => NULL,
      ),
    ),
    'swaptable' => array(
      'render element' => 'element',
      'template' => 'theme/swaptable',
      'file' => 'theme/theme.inc',
    ),
  );
}

/**
 * Implements hook_element_info().
 */
function islandora_paged_content_element_info() {
  $module_path = drupal_get_path('module', 'islandora_paged_content');
  return array(
    'swaptable' => array(
      '#input' => TRUE,
      '#pager' => array(
        // Pager ID's you may need to override this value if there are already
        // several pagers on the page.
        'element' => array(0, 1),
        'tags' => array('<<', '<', '', '>', '>>'),
        'limit' => 10,
        'quantity' => 3,
        'total' => 0,
      ),
      '#prefix' => '<div class="swaptable-wrapper">',
      '#suffix' => '</div>',
      '#attributes' => array(
        'class' => array('swaptable'),
      ),
      '#theme' => 'swaptable',
      '#theme_wrappers' => array('form_element'),
      '#value_callback' => 'swaptable_value',
      '#attached' => array(
        'js' => array($module_path . '/js/swaptable.js'),
        'css' => array($module_path . '/css/islandora_paged_content.swaptable.css'),
        'library' => array(
          array('system', 'jquery.cookie'),
          array('system', 'ui.draggable'),
          array('system', 'ui.droppable'),
          array('system', 'ui.sortable'),
          array('system', 'ui.selectable'),
        ),
      ),
    ),
  );
}

/**
 * Determine whether or not to show this modules manage tab.
 *
 * @return bool
 *   TRUE if they can access, FALSE otherwise.
 */
function islandora_paged_content_manage_page_access_callback($object, array $content_models) {
  $permissions = array(
    ISLANDORA_ADD_DS,
    ISLANDORA_METADATA_EDIT,
    ISLANDORA_PURGE,
  );
  return islandora_user_access($object, $permissions, $content_models);
}

/**
 * Checks whether the user can access the "manage pages" page.
 *
 * @return bool
 *   TRUE if they can access, FALSE otherwise.
 */
function islandora_paged_content_manage_pages_access_callback($object, array $content_models) {
  $permissions = array(
    ISLANDORA_ADD_DS,
    ISLANDORA_METADATA_EDIT,
    ISLANDORA_PURGE,
    ISLANDORA_INGEST,
  );
  return islandora_user_access($object, $permissions, $content_models);
}

/**
 * Implements hook_permission().
 */
function islandora_paged_content_permission() {
  return array(
    ISLANDORA_PAGED_CONTENT_EDIT_OCR => array(
      'title' => t('Edit OCR stream'),
      'description' => t('Allows users to edit existing OCR stream. Note: Fedora XACML security policies may override this permission.'),
    ),
  );
}

/**
 * Implements form_type_hook_value().
 */
function swaptable_value($element, $input, array $form_state) {
  if ($input !== FALSE) {
    return explode(' ', $input);
  }
  else {
    $value = isset($element['#default_value']) ?
      $element['#default_value'] :
      element_children($element['#rows']);
    return implode(' ', $value);
  }
}
