<?php
/**
 * @file
 * This is the main file for a module supporting paged content for Islandora.
 */

function islandora_paged_content_menu() {
  $out = array(
    'admin/islandora/paged_content' => array(
      'title' => 'Paged Content Module',
      'description' => 'Configuration for the Paged Content solution pack.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_paged_content_admin_settings_form'),
      'access arguments' => array('administer site configuration'),
      'file' => 'includes/admin.form.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
  );

  return $out;
}

/**
 * This function will search a Fedora's object datastream's HOCR content for a
 * given term and return coordinate data. It only works on exact term matches.
 *
 * @param IslandoraFedoraObject $fedora_object
 *   The object to apply the search to.
 * @param string $term
 *   The term to search for.
 * @param string $hocr_dsid
 *   The HOCR datastream id.
 *
 * @return array
 *   $highlighting_info The coordinates of the matches to the term.
 */
function islandora_paged_content_get_highlighting_info($fedora_object, $term, $hocr_dsid = 'ENCODED_OCR') {
  $boxes = array();
  // Return nothing if the DSID is not populated.
  if (!isset($fedora_object[$hocr_dsid])) {
    return array();
  }

  // Return nothing if the XML is not populated.
  $hocr_xml = @simplexml_load_string($fedora_object[$hocr_dsid]->content);
  if (!$hocr_xml) {
    return array();
  }

  $lower_term = strtolower($term);
  $lower_term = urldecode($lower_term);
  $terms = explode(' ', $lower_term);
  foreach ($terms as $term) {
    $matches = $hocr_xml->xpath("//node()[local-name() = 'span'][translate(text(),'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')='{$term}']/..");
    foreach ($matches as $match) {
      $bbox = (string) $match['title'];
      $values = explode(' ', $bbox);
      $boxes[] = array(
        'left' => intval($values[1]),
        'top' => intval($values[2]),
        'right' => intval($values[3]),
        'bottom' => intval($values[4]),
      );
    }
  }
  $highlighting_info['bounding_boxes'] = $boxes;

  $page_matches = $hocr_xml->xpath("//node()[local-name() = 'div'][@class='ocr_page']");
  foreach ($page_matches as $match) {
    $page_dimensions = (string) $match['title'];
    $values = explode(' ', $page_dimensions);
    $highlighting_info['width'] = intval($values[5]);
    $highlighting_info['height'] = intval($values[6]);
  }

  return $highlighting_info;
}

/**
 * Determine whether or not to show this modules manage tab.
 *
 * @param FedoraObject $object
 *   The object being managed.
 *
 * @return bool
 *   TRUE if it should be shown, and FALSE if it should not be shown.
 */
function islandora_paged_content_manage_page_access_callback($object = NULL) {
  if (!isset($object)) {
    return FALSE;
  }
  $manage_actions = array(
    FEDORA_ADD_DS,
  );
  $can_access = function($perm) use($object) {
    return  islandora_object_access_callback($perm, $object);
  };
  $can_manage = count(array_filter($manage_actions, $can_access));
  $is_page = in_array('islandora:pageCModel', $object->models);
  $is_page |= in_array('islandora:newspaperPageCModel', $object->models);
  $is_page |= in_array('islandora:bookPageCModel', $object->models);
  return $is_page && $can_manage;
}
